### ISSUE TITLE
rerender webservice sometimes fails

### ISSUE THREAD

**Issue by isuruf** [conda-forge/status#60] opened 2019-10-01 18:14 UTC
This is due to heroku instance running out of memory.

**Comment by CJ-Wright** [comment] 2019-10-01 18:17
Do we have a badge we can put on the status page?

**Comment by isuruf** [comment] 2019-10-01 18:20
This issue is supposed to do that, but it fails with

2019-10-01T18:17:56.625008+00:00 app[web.1]: github.GithubException.GithubException: 422 {'message': 'path cannot start with a slash', 'errors': [{'resource': 'Commit', 'field': 'path', 'code': 'invalid'}], 'documentation_url': 'https://developer.github.com/v3/repos/contents/#create-or-update-a-file'}

**Comment by jakirkham** [comment] 2019-10-01 18:34
> This issue is supposed to do that, but it fails with

It is. Ouch! 🤦‍♂

**Comment by jakirkham** [comment] 2019-10-03 15:37
Potentially related our slug size is pretty large. ( https://github.com/conda-forge/conda-forge-webservices/issues/261 )

**Comment by beckermr** [comment] 2020-02-02 01:02
@isuruf @jakirkham are we good to close this one? The issue is out of date and the status page is now fully automated so we won't need to make issues here anymore.

**Comment by scopatz** [comment] 2020-02-03 18:12
Feel free to reopen if needed!

**Closed by scopatz** 2020-02-03 18:12 UTC
Labels: degraded performance, linter
